version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
